version: '3'

services:

  centos7:
    build: .
    volumes:
      - ./src:/opt/code
    command: ./bin/entrypoint.sh
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 4000M
        reservations:
          cpus: '2'
          memory: 4000M
