#ifndef HC_C1_ALL_TESTS_H
#define HC_C1_ALL_TESTS_H

void test_produzioneNonBloccateInUnBufferGiaPieno();
void test_consumazioneBloccanteDaUnBufferInizialmenteVuoto();
void test_produzioneDiUnSoloMessaggioInUnBufferVuoto();
void test_consumazioneDiUnSoloMessaggioDaUnBufferPieno();
void test_consumazioneDaUnBufferVuoto();
void test_produzioneInUnBufferPieno();
void test_consumazioneEProduzioneConcorrenteDiUnMessaggioDaUnBufferUnitarioPrimaIlConsumatore();
void test_consumazioneEProduzioneConcorrenteDiUnMessaggioInUnBufferUnitarioPrimaIlProduttore();
void test_produzioneConcorrenteDiMoltepliciMessaggiInUnBufferUnitarioVuoto();
void test_consumazioneConcorrenteDiMoltepliciMessaggiDaUnBufferUnitarioPieno();
void test_produzioneConcorrenteDiMoltepliciMessaggiInUnBufferVuotoIlBufferNonSiRiempie();
void test_produzioneConcorrenteDiMoltepliciMessaggiInUnBufferPienoIlBufferEGiaSaturo();
void test_produzioneConcorrenteDiMoltepliciMessaggiInUnBufferVuotoIlBufferSiSaturaInCorso();
void test_consumazioneConcorrenteDiMoltepliciMessaggiDaUnBufferPieno();
void test_consumazioniEProduzioniConcorrenteDiMoltepliciMessaggiInUnBufferUnitario();
void test_consumazioniEProduzioniConcorrenteDiMoltepliciMessaggiInUnBuffer();
void test_msgCopyConUnIntero();
void test_msgCopyConUnaString();

#endif
